api_version = "2026-01"

[[extensions]]
name = "Simple Product Discount"
handle = "simple-product-discount"
type = "function"
description = "Applies one simple percentage product discount"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.input.variables]
  namespace = "$app:simple-product-discount"
  key = "function-configuration"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
